name: test
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: ${{GITHUB_SHA}}
